### ISSUE TITLE
Language changes

### ISSUE THREAD

**Issue by Floxn** [oveleon/contao-component-style-manager#1]
Hey, i have tested your extension. I like :)

Maybe you can change the words in your manager:
key -> class
and 
value -> class title, class name or something like that.

I think it is a bit confusing.

<img width="552" alt="Bildschirmfoto 2019-11-27 um 09 26 24" src="https://user-images.githubusercontent.com/15326334/69706437-0466c800-10f8-11ea-9e7d-b2998cee3660.png">

**Comment by doishub** [comment]
Thank you Floxn.

I'm currently working on a bigger update, which I'll realease soon. I will then implement your wish directly. ;-)

**Comment by doishub** [comment]
Fixed in https://github.com/oveleon/contao-component-style-manager/commit/82caddf9ed49e477b7dc30e937bac6241c15c7a2
