### ISSUE TITLE
Illegal string offset 'id'

### ISSUE THREAD

**Issue by ro-a-fi** [oveleon/contao-component-style-manager#15]
Since the last Update (from 2.0.1 to the current) I get a warning for some articles (frontend and backend), when I try to edit the article settings. Somehow not all articles are affected.

<img width="1142" alt="Bildschirmfoto 2020-01-25 um 15 20 01" src="https://user-images.githubusercontent.com/6197911/73122541-6c198200-3f86-11ea-9558-ac67c8429b11.png">

Is there a way to fix this? Any help is appreciated!

**Comment by doishub** [comment]
Many thanks for the report. In the course of the expansion, we have changed the storage of the data, from aliases to ID's. Apparently old data sets were not converted uniformly. With the new release, however, the error should also be intercepted. 

Could you please make an update and check if it works now?

**Comment by ro-a-fi** [comment]
Thanks for your quick reply and fix. Everythings works fine now, great development.
