### ISSUE TITLE
Contao 4.9.2 kompatibilität

### ISSUE THREAD

**Issue by sebssch** [oveleon/contao-component-style-manager#20]
Ich habe das Modul bei einem Projekt mit Contao 4.9.1 im Einsatz. Hier hat alles wunderbar funktioniert.
 
Nach einem Update auf 4.9.2 werden die Klassen-Einstellungen nicht mehr ans Template übergeben. 

Das entfernen einer bestehenden Klasse funktioniert. 
Beim Versuch die Klasse wieder auszuwählen und somit erneuten hinzuzufügen scheitert jedoch.

**Comment by doishub** [comment]
Hat doch alles funktioniert oder gibt es noch Probleme? In unseren Projekten konnten wir bisher keine Fehler nach einem update auf die 4.9.2 feststellen.

**Comment by sebssch** [comment]
Es hat nach einem Composer install alles wieder funktioniert. 🙈
Trotzdem Danke für die schnelle Antwort. Super Hilfreiche Erweiterung!
