### ISSUE TITLE
Add base class per category

### ISSUE THREAD

**Issue by andreheeke** [oveleon/contao-component-style-manager#29]
It would be helpful if there is in each category the possibility to add one or more base classes, which will be added at the beginning in any case when selecting a CSS group.

**Comment by doishub** [comment]
Is this feature still needed? In our case we solve this by simply adding two values:

![image](https://user-images.githubusercontent.com/48379929/97176464-462f4100-1795-11eb-8f22-2c8f8e39ee53.png)

Or could you describe the use case why this is not sufficient in your case?

**Comment by doishub** [comment]
I will close it for now, feel free to reopen if necessary.
