### ISSUE TITLE
Cannot use object of type Oveleon\ContaoComponentStyleManager\Styles as array

### ISSUE THREAD

**Issue by ro-a-fi** [oveleon/contao-component-style-manager#4]
I really like your extension, it's great for a customizable frontend. I directly installed the new Version 2.0 today to test the new features.

At first sight everything worked fine, but now, when I want to edit an article containing an element with an image (or showing the same element in the frontend), it gives me the error "Cannot use object of type Oveleon\ContaoComponentStyleManager\Styles as array". The same thing shows up, if I change the content type of an element from text to image and then click "save and close".

![Bildschirmfoto 2020-01-10 um 01 42 19](https://user-images.githubusercontent.com/6197911/72116556-df967f00-334a-11ea-8c47-8b03e2be9926.png)
![Bildschirmfoto 2020-01-10 um 01 44 20](https://user-images.githubusercontent.com/6197911/72116557-e02f1580-334a-11ea-9c3a-077799109505.png)

The respective log file output is
`[2020-01-10 00:50:19] request.CRITICAL: Uncaught PHP Exception Error: "Cannot use object of type Oveleon\ContaoComponentStyleManager\Styles as array" at /Users/Raphael/Development/rl-contao-theme-multi/vendor/oveleon/contao-component-style-manager/src/Resources/contao/classes/StyleManager.php line 342 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Cannot use object of type Oveleon\\ContaoComponentStyleManager\\Styles as array at /Users/Raphael/Development/rl-contao-theme-multi/vendor/oveleon/contao-component-style-manager/src/Resources/contao/classes/StyleManager.php:342)"} []`

Is there a way you could fix this? I would really like to continue to use your extension.

**Comment by doishub** [comment]
Thanks for your feedback and testing the extension. I have fixed the error in https://github.com/oveleon/contao-component-style-manager/commit/660d9fce401330c2bb60bbd0fe149e1bbb8b7b64. I have created a new Realease 2.0.1.
