### ISSUE TITLE
Attempt to assign property "styleManager" on null

### ISSUE THREAD

**Issue by Ma3xl3** [oveleon/contao-component-style-manager#57]
Hi. First thx for your cool extension.

Since the update 2.6.2 i get the following error in the frontend.

```
Error:
Attempt to assign property "styleManager" on null

  at vendor/oveleon/contao-component-style-manager/src/Resources/contao/classes/StyleManager.php:393
  at Oveleon\ContaoComponentStyleManager\StyleManager->onGeneratePage(object(PageModel), object(LayoutModel), object(PageRegular))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:191)
  at Contao\PageRegular->prepare(object(PageModel))
     (vendor/contao/core-bundle/src/Resources/contao/pages/PageRegular.php:48)
  at Contao\PageRegular->getResponse(object(PageModel), true)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/FrontendIndex.php:337)
  at Contao\FrontendIndex->renderPage(object(PageModel))
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/index.php:31)
```

If i downgrade to 2.6.1, everything works fine.
I´m running contao 4.9.24 with php 8.0

**Comment by Tastaturberuf** [comment]
Its [#56](https://github.com/oveleon/contao-component-style-manager/commit/7475cf07a74347872ca9ad36023bababb259c090#diff-f0e6d7170ea2cd4b716a1e3a2300cdd8077c84a8fcb274be9a0c02c34c129263R393) the `Template`-property is `protected`.

**Comment by doishub** [comment]
I think I have found a solution to extend the object elsewhere. Could you test the `dev-develop` branch please?

**Comment by Tastaturberuf** [comment]
Error is gone. But I have not tested if the variables are set correctly for this feature.

**Comment by doishub** [comment]
I could already check that ;)

Then I'll create the new release right away, thanks for testing!

**Comment by doishub** [comment]
Fixed in https://github.com/oveleon/contao-component-style-manager/commit/034fcf199c4f34ae4a2d4d9269870f33f7c4b480

**Comment by Tastaturberuf** [comment]
Thx
