### ISSUE TITLE
Contao 4.13 RC2 and Stylemanager

### ISSUE THREAD

**Issue by mlwebworker** [oveleon/contao-component-style-manager#59]
Bei Test einer Installation mit Contao 4.13 RC2 mit dem Style-Manager ist mir aufgefallen, dass sich folgende Tabelle im Installtool nicht ändern lässt:

`ALTER TABLE tl_style_manager CHANGE alias alias VARCHAR(255) DEFAULT '' NOT NULL COLLATE 'utf8_bin'
`

Ist das ein Problem in meinen Einstellungen oder tatsächlich ein Problem der Erweiterung?
Im Backend und im Frontend konnte ich auf den ersten Blick keinerlei Fehler feststellen.
Im Debug-Modus gibt es auch keine Fehler.

Contao 4.13 RC2
XAMPP mit PHP 7.4.27
Windows 10

**Comment by mlwebworker** [comment]
Danke

**Comment by zoglo** [comment]
@mlwebworker Der Fehler ist mit Version 2.6.4 behoben

**Comment by mlwebworker** [comment]
Danke fürs schnelle Fixen
