### ISSUE TITLE
Standardscope in Kategorien einstellen

### ISSUE THREAD

**Issue by vossmedien** [oveleon/contao-component-style-manager#64]
Hey,
mir ist eine Sache aufgefallen - evtl. ist das ja ein Feature wert :-)
ich arbeite sehr viel mit eigenen Inhaltselementen und da ist es immer recht mühsam hinterher in jeder CSS-Gruppe das neue Inhaltselement neu auszuwählen.
Eventuell gibt es ja die Chance, dass man bei den Kategorien bereits die Elemente auswählen kann und das dann automatisch auf die Unterelemente angewandt wird.

Danke, ansonsten super Erweiterung :-)

**Comment by ngdot** [comment]
Hi, genau das gleiche Problem habe ich auch. Es ist ziemlich mühselig das in allen Kategorie/Gruppen zu ändern.

Habe dazu folgende, Idee (basierend auf der Erweiterung von [craffft](https://github.com/Craffft/css-style-selector-bundle)):

Mein Vorschlag wäre es, den Style-Manager erstmal in allen Kategorien standardmäßig zu aktivieren. Also in allen Inhaltselementen, Artikeln, Modulen etc.

Anschließend kann man wählen wo er NICHT aktiv sein soll, im ersten Schritt für eine ganze Kategorie, im zweiten dann mit Subauswahl für bestimmte Elemente. Also quasi das Gegenteil von der aktuellen Umsetzung. 

Habe das ganze mal visualisiert, damit man es besser versteht.

![screenshot-andr-2022 07 22-11_47_17](https://user-images.githubusercontent.com/8327905/180413504-dbcc6889-8b98-485b-8358-be23f7b5e7cd.png)

**Comment by c4y** [comment]
Ich brauche das auch dringend :-) Würde auch ein Pull-Request erstellen. Mein Ansatz wäre, in jeder Gruppe eine zusätzliche Checkbox einbauen "Auswahl invertieren". Dann wäre man flexibler und hätte beide Welten. Die Änderung wäre auch minimal. ABER: ich weiß (noch) nicht, wie ich mit den Bundle-Konfigurationen (Merge) umgehen soll. Es werden ja alle Felder gemerged.

**Comment by doishub** [comment]
Das müsste man mal ausprobieren, aber m.E. sollte das mergen mit jeglichen Felder funktionieren. Schau mal in die beiden Models und in folgende Methode:
https://github.com/oveleon/contao-component-style-manager/blob/cc737da7767356b1c98376dedbb7a5ab03ba3014/src/StyleManager/Sync.php#L145

**Comment by c4y** [comment]
Ja, kenne ich. Nur wie geht man mit folgender Situation um:
Die config im Bundle hat kein "invertieren" ausgewählt, meine manuelle Config aber schon. Dann hätte ich am Ende im schlimmsten Fall keine Element mehr, was angezeigt wird.
Beispiel mit 3 Inhaltselementen:
Bundle: Element 1 und 3 ausgewählt (ohne Invertierung)
eigene Config: Element 2 ausgewählt (mit Invertierung)
Gemerged wären alle drei Elemente ausgewählt. Durch die Invertierung dann am Ende kein Element. Die Prüfung, welches Element angezeigt wird erfolgt ja erst nach dem Merge.

**Comment by c4y** [comment]
Daher müsste ich in der mergeGroupObjects bereits je nach Invertierung des Bundle-Objekts die Felder der verfügbaren Elemente invertieren. Diese Felder müsste man dann noch irgendwo hinterlegen (Module, Inhaltselemente, Forms, etc). Z.B. in der config.php?

**Comment by doishub** [comment]
Ja, das ist alles nicht so optimal. Ich würde fast sagen, man muss sich dafür entscheiden, welche Variante man in seinen Projekten nutzen möchte und dies ggf. über die `config.yaml` definieren. Standard sollte hier der bisherige Weg sein, zwecks Updatekompatibilität.

```yaml
// config.yaml
contao_component_style_manager:
    invert_component_selection: false
```

Man könnte es auch in die CSS-Gruppen mit rein holen, um hier immer eine exakte Prüfung durchzuführen, aber ich befürchte, dass wird zu weiteren Problemen führen.

**Comment by zoglo** [comment]
I'll keep this issue open but it doesn't seem that anything has been done within the past 8 months regarding the previous PR that wasn't updated anymore and would also need extra attention to be merged into the current branch.

**Comment by zoglo** [comment]
@vossmedien @ngdot @c4y 

Da ich damals teils 500 Checkboxen anklicken musste pro neues RSCE habe ich mir damals ein Bookmarklet geschrieben.
Da wir seit Längerem nicht mehr mit StyleManager-Archiven sondern der neuen Bundle-Konfiguration arbeiten, möchte ich dieses Bookmarklet / Snipplet nicht vorenthalten.

Dieses lässt sich als Bookmark in eurem Browser ergänzen [(Tutorial)](https://www.freecodecamp.org/news/what-are-bookmarklets/)
https://gist.github.com/zoglo/f0458b7749d264f9191a964c5884f3e3

1. Öffnet per Massenbearbeitung alle StyleManager-Kindselemente in einem Archiv und wählt Modul / Element (was auch immer ihr anklicken wollt) aus.
2. Bei Klick darauf könnt ihr das Element / Modul eintragen (z.B. form / rsce_text) und es klickt euch alle Checkboxen des Elements an, speichert den Eintrag und verlässt die Seite wieder.
![image](https://github.com/oveleon/contao-component-style-manager/assets/55794780/ab4915c9-8271-4d74-a9c9-a9770b0ced87)

Der Pull-Request wurde nach dem Review nicht mehr weiter entwickelt. Ich würde dieses Issue mit dem Bookmarklet schließen.
Sofern Bedarf besteht, gerne wieder öffnen.
