### ISSUE TITLE
Bootstrap template

### ISSUE THREAD

**Issue by Mangaclub** [oveleon/contao-component-style-manager#87]
Would you be able to supply a importable Template for bootstrap on installation?

**Comment by doishub** [comment]
We ourselves do not work with Bootstrap, however you can do it yourself. Build the set you want to reuse and export it.

This export file can be imported and used in any project. In addition, these configurations can be provided by the Bundle-Config also automatically for when installing a bundle:
https://github.com/oveleon/contao-component-style-manager/blob/master/docs/BUNDLE_CONFIG.md

**Comment by doishub** [comment]
If you want to deploy the set, you can create an extension for everyone in which this bundle configuration is delivered. This way it is only one dependency away for others to use your config 😉

**Comment by zoglo** [comment]
@Mangaclub feel free to create a bundle config for bootstrap classes and share your repository in here.

I'll close this now as it's neither an issue or a feature request.
