### ISSUE TITLE
Controller / Route Problem

### ISSUE THREAD

**Issue by rorych** [oveleon/contao-component-style-manager#95]
### Prerequisites

- [X] I [checked](https://github.com/oveleon/contao-component-style-manager/issues?q=is%3Aissue) for duplicate issues (open and closed)
- [X] I am using the latest stable [version/release](https://packagist.org/packages/oveleon/contao-component-style-manager) of the Contao Component Style Manager
- [X] I have read the [contributing guidelines](https://github.com/oveleon/contao-component-style-manager#bugs-and-feature-requests)

### Please select the topic(s) that most closely match your concern

Backend (PHP/CSS)

### Description

Contao: 5.2.7
PHP 8.1.25
oveleon/contao-component-style-manager: 3.4.2

--

After composer update from Contao 5.2.6 to 5.2.7 (and all the symfony upgrades to v6.4.0) your bundle is throwing following error on cache clear.
Can you help me with this?

### Relevant log output

```shell
In FileLoader.php line 182:
  Route alias "Oveleon\ContaoComponentStyleManager\Controller\BackendModule\I  
  mportController" can not reference itself in vendor/oveleon/contao-component-style-manager/src/Controller (which is be  
  ing imported from "/vendor/oveleon/contao-co  
  mponent-style-manager/src/ContaoManager/../Resources/config/routes.yaml").   
  Make sure there is a loader supporting the "annotation" type.  
```

```
In RouteCollection.php line 375:
  Route alias "Oveleon\ContaoComponentStyleManager\Controller\BackendModule\I  
  mportController" can not reference itself.     
```
```

**Comment by fritzmg** [comment]
It appears you are missing `contao/conflicts` in your `composer.json`. You need to add that and then run a `composer update`.

**Comment by rorych** [comment]
Thanks for the fast reply, i have following in my composer.json:
`"contao/conflicts": "@dev"`

Would you recommend to have a version set?

**Comment by fritzmg** [comment]
No, `@dev` is correct. Anyway, this error is unrelated to this extension. The error is caused by `symfony/routing: 6.4.0`, see https://github.com/symfony/symfony/issues/52801. This is why a conflict was added in `contao/conflicts`: https://github.com/contao/conflicts/pull/55. Run a full `composer update`, then `symfony/routing` should automatically be downgraded.

**Comment by fritzmg** [comment]
Why did you set the minimum stability lower?

**Comment by rorych** [comment]
Because of custom bundles, that are still in development.
