### ISSUE TITLE
Doppelte oder falsche Einträge nach Import

### ISSUE THREAD

**Issue by csaeum** [oveleon/contao-component-style-manager#99]
### Prerequisites

- [X] I [checked](https://github.com/oveleon/contao-component-style-manager/issues?q=is%3Aissue) for duplicate issues (open and closed)
- [X] I am using the latest stable [version/release](https://packagist.org/packages/oveleon/contao-component-style-manager) of the Contao Component Style Manager
- [X] I have read the [contributing guidelines](https://github.com/oveleon/contao-component-style-manager#bugs-and-feature-requests)

### Please select the topic(s) that most closely match your concern

Template (HTML/Twig)

### Description

Ich habe gerade ein Contao LTS 5.3.7 installiert mit ThemeManager und Komponenten StyleManager

Habe dann in den StyleManager alles importiert.

Wenn ich nun den Manager nutzen möchte sehe ich Einträge doppelt und manche gar nicht. Denke aber das hinter einen der doppelten Einträge der nicht zu sehene Eintrag ist.

Einmal ein paar Screenshots vom StyleManager Admin und vom Layout Bereich wo man diesen nutzt.

![ThemeManager--1--2024-05-04-](https://github.com/oveleon/contao-component-style-manager/assets/1543510/dca1ed6c-9843-4b05-ae5a-f4d8f9f8eb26)
![ThemeManager--2--2024-05-04-](https://github.com/oveleon/contao-component-style-manager/assets/1543510/1db4bcbb-447f-4882-8d0f-8285afbd5beb)
![ThemeManager--3--2024-05-04-](https://github.com/oveleon/contao-component-style-manager/assets/1543510/529feafc-7a19-4ad9-b57b-abb846b25a84)
![ThemeManager--4--2024-05-04-](https://github.com/oveleon/contao-component-style-manager/assets/1543510/6ffda149-c8f8-42c7-9c34-5f59546a11bf)

### Relevant log output

```shell
Hier habe ich keinen Output
```

**Comment by zoglo** [comment]
@csaeum 

Der Contao-ThemeManager nutzt die StyleManager Bundle-Config, welche im Contao-ThemeManager automatisch importiert wird und in die Komponenten integriert wird.

Wenn du die Konfiguration über die StyleManager-Archive importierst, werden diese natürlich doppelt angelegt.
Für die Verwendung des Contao-ThemeManagers musst du die Konfigurationen nicht importieren, lösche diese einfach, da es sich hierbei um Experten-Einstellungen handelt ;)

**Comment by zoglo** [comment]
> Habe dann in den StyleManager alles importiert.

Das wird in der Dokumentation nicht behandelt und auch nicht empfohlen - Einfach alle Archive löschen, dann sollte alles laufen :)

**Comment by zoglo** [comment]
@csaeum 
This will be fixed with the next release - See #100 

> [!CAUTION]
> Please delete your imported archives since **you'd lose the ability to receive bugfixes** when we update the contao-thememanager


Having the archives imported into your database will make sure you lose the ability to receive any future updates (same concept as overwriting templates from Contao)
